name: release
on:
  push:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.tag.outputs.tag_name }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Generate tag name
        id: tag
        run: |
          TAG_NAME=$(date -u +%Y.%m.%d)-${GITHUB_SHA:0:7}
          echo "tag_name=${TAG_NAME}" >> $GITHUB_OUTPUT

  linux:
    needs: setup
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.build.outputs.version }}
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 0
      - run: ./.github/scripts/install_deps.sh
      - run: echo "CMAKE_BUILD_TYPE=Release" >> $GITHUB_ENV
      - name: Build deps
        run: |
          cmake -S cmake.deps -B .deps -G Ninja -D CMAKE_BUILD_TYPE=Release
          cmake --build .deps
      - name: Build neovim
        run: |
          cmake -B build -G Ninja -D CMAKE_BUILD_TYPE=Release
          cmake --build build
      - name: Package
        run: cpack --config build/CPackConfig.cmake -G TGZ
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: nvim-linux-x86_64
          path: build/nvim-linux-x86_64.tar.gz
          retention-days: 1
      - name: Export version
        id: build
        run: |
          printf 'version<<END\n' >> $GITHUB_OUTPUT
          ./build/bin/nvim --version | head -n 3 >> $GITHUB_OUTPUT
          printf 'END\n' >> $GITHUB_OUTPUT

  macos:
    needs: setup
    runs-on: macos-14
    env:
      MACOSX_DEPLOYMENT_TARGET: 11.0
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: ./.github/scripts/install_deps.sh
      - name: Build deps
        run: |
          cmake -S cmake.deps -B .deps -G Ninja \
            -D CMAKE_BUILD_TYPE=Release \
            -D CMAKE_FIND_FRAMEWORK=NEVER
          cmake --build .deps
      - name: Build neovim
        run: |
          cmake -B build -G Ninja \
            -D CMAKE_BUILD_TYPE=Release \
            -D ENABLE_LIBINTL=OFF \
            -D CMAKE_FIND_FRAMEWORK=NEVER
          cmake --build build
      - name: Package
        run: cpack --config build/CPackConfig.cmake
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: nvim-macos-arm64
          path: build/nvim-macos-arm64.tar.gz
          retention-days: 1

  publish:
    needs: [setup, linux, macos]
    runs-on: ubuntu-latest
    env:
      GH_REPO: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y gettext-base
      - name: Set tag name
        run: echo "TAG_NAME=${{ needs.setup.outputs.tag_name }}" >> $GITHUB_ENV
      - name: Publish release
        env:
          NVIM_VERSION: ${{ needs.linux.outputs.version }}
          NVIM_COMMIT: ${{ github.sha }}
        run: |
          envsubst < "$GITHUB_WORKSPACE/.github/workflows/notes.md" > "$RUNNER_TEMP/notes.md"
          gh release create $TAG_NAME --notes-file "$RUNNER_TEMP/notes.md" --title "Snapshot $TAG_NAME" --target $GITHUB_SHA nvim-linux-x86_64/* nvim-macos-arm64/*
